# Generated by Django 2.2 on 2020-11-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='contact_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
