# Generated by Django 2.2 on 2020-11-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntBuddyApp', '0002_contactperson_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupdate',
            name='last_follow_up',
            field=models.DateField(null=True),
        ),
    ]
