# Generated by Django 2.2 on 2020-11-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntBuddyApp', '0004_auto_20201129_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person', to='jobHuntBuddyApp.Position'),
        ),
    ]
